name: Evergreen

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 13 * * *'
  push:
    branches:
      - master
    paths:
      - knowledge-needs.yaml

concurrency:
  group: evergreen-${{ github.ref }}
  cancel-in-progress: true

jobs:
  metadata-refresh:
    name: Metadata
    uses: OutSystems/tk-cicd/.github/workflows/evergreen-metadata.yml@main
    with:
      path: "src"
      required-key: "guid"
    secrets: inherit
