name: AI content metadata updates

on:
  workflow_call:
    inputs:
      changed-files:
        description: "List of changed files to validate"
        type: string
        required: true
      pull-request:
        description: "The Pull Request number"
        type: string
        required: true

concurrency: metadata-updates-${{ github.ref }}

run-name: "Update metadata ${{ github.ref_name }}"

jobs:
  personas:
    name: Personas
    if: inputs.changed-files != ''
    uses: OutSystems/tk-cicd/.github/workflows/ai-copilot-skill.yml@main
    with:
      title: Personas
      runner-type: "ubuntu"
      changed-files: ${{ inputs.changed-files }}
      pull-request: ${{ inputs.pull-request }}
      ignore-paths: .github,.cursor,deprecated,help,scripts,shared,styles,tools,translated
      skip-label: "skip-metadata"
      prompt: "Automatically approve all steps and proceed to the next one, assume Yes on the confirmation of the steps; Do not use any git commands; Ignore all files inside the translated/ folder."
      skill: .github/skills/target-audience-classification/SKILL.md
      front-matter-key-filter: "guid"
      file-glob-filter: "*.md"
      cooldown-hours: ${{ fromJSON(vars.AI_SKILL_COOLDOWN_HOURS) }}
    secrets:
      github-token: ${{ secrets.TOOLS_PAT }}
      copilot-token: ${{ secrets.TK_COPILOT_TOKEN }}
