name: Run

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - main
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled, ready_for_review, converted_to_draft]

concurrency:
  group: run-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-info:
    name: Pull Request / Info
    uses: OutSystems/tk-cicd/.github/workflows/pr-info.yml@main
    secrets: inherit

  jira:
    name: "JIRA"
    needs: [pr-info]
    if: needs.pr-info.outputs.pull-request != ''
    uses: OutSystems/tk-cicd/.github/workflows/jira-issue-pr.yml@main
    secrets: inherit
    with:
      pull-request: ${{ needs.pr-info.outputs.pull-request }}
      product-type: O11

  visual-assets:
    name: "Visual Assets"
    needs: [pr-info]
    if: needs.pr-info.outputs.pull-request != ''
    uses: OutSystems/tk-cicd/.github/workflows/visual-assets-pr.yml@main
    secrets: inherit
    with:
      pull-request: ${{ needs.pr-info.outputs.pull-request }}
      files: ${{ needs.pr-info.outputs.changed-files }}
  
  style-guide-validation:
    name: Style Guide
    needs: [pr-info]
    if: needs.pr-info.outputs.changed-files != ''
    uses: OutSystems/tk-cicd/.github/workflows/style-guides-validation.yml@main
    with:
      runner-type: "ubuntu-latest"
      changed-files: ${{ needs.pr-info.outputs.changed-files }}
      pull-request: ${{ needs.pr-info.outputs.pull-request }}
      disable-suggestions: ${{ fromJSON(vars.DISABLE_STYLE_GUIDE_SUGGESTIONS) }}
    secrets:
      github-token: ${{ secrets.TOOLS_PAT }}
      copilot-token: ${{ secrets.TK_COPILOT_TOKEN }}

  validate-toc:
    name: Validate files in TOC
    needs: [pr-info, jira]
    if: needs.pr-info.outputs.changed-files != ''
    uses: OutSystems/tk-cicd/.github/workflows/validate-toc.yml@main
    with:
      changed-files: ${{ needs.pr-info.outputs.changed-files }}
    secrets: inherit

  auto-publish-documentation:
    name: Auto-publish documentation
    needs: [pr-info, jira]
    if: github.event_name == 'pull_request' && needs.pr-info.outputs.changed-files != '' && github.event.pull_request.base.ref == github.event.repository.default_branch
    uses: OutSystems/tk-cicd/.github/workflows/auto-publish-documentation.yml@main
    with:
      changed-files: ${{ needs.pr-info.outputs.changed-files }}
      pr-number: ${{ needs.pr-info.outputs.pull-request }}
      base-sha: ${{ github.event.pull_request.base.sha }}
      enable_auto_publish_new_files: ${{ vars.ENABLE_AUTO_PUBLISH_NEW_FILES != '' && vars.ENABLE_AUTO_PUBLISH_NEW_FILES || 'true' }}
      enable_auto_publish_updated_files: ${{ vars.ENABLE_AUTO_PUBLISH_UPDATED_FILES != '' && vars.ENABLE_AUTO_PUBLISH_UPDATED_FILES || 'true' }}
    secrets:
      github-token: ${{ secrets.TOOLS_PAT }}

  auto-fill:
    if: github.event_name == 'pull_request'
    uses: OutSystems/tk-cicd/.github/workflows/autofill-frontmatter.yml@main
    needs: [pr-info, jira]
    with:
      GITHUB_REPOSITORY: ${{ github.repository }}
      PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      ACTION_TYPE: ${{ github.event.action }}  # Pass the action type (opened or synchronize)
      BEFORE_SHA: ${{ github.event.before }}   # Pass the SHA of the commit before the synchronization
      AFTER_SHA: ${{ github.event.after }}
      BASE_BRANCH: ${{ github.event.pull_request.base.ref }}  # Base branch of the pull request
      HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}  # Head branch of the pull request 
    secrets: inherit

  frontmatter:
    name: Frontmatter
    uses: OutSystems/tk-cicd/.github/workflows/validate-frontmatter.yml@main
    needs: [pr-info, auto-fill]
    secrets: inherit

  validations:
    name: Misc validations
    needs: [pr-info, jira]
    uses: OutSystems/tk-cicd/.github/workflows/validations.yml@main
    secrets: inherit
    with:
      GITHUB_REPOSITORY: ${{ github.repository }}
      PR_NUMBER: ${{ needs.pr-info.outputs.pull-request }}
      TK_CICD_BRANCH: 'main'

  ai-skills:
    name: AI Skills
    needs: [pr-info, tools]
    uses: OutSystems/tk-cicd/.github/workflows/ai-skills.yml@main
    with:
      changed-files: ${{ needs.pr-info.outputs.changed-files }}
      pull-request: ${{ needs.pr-info.outputs.pull-request }}
      runner-type: ubuntu
      front-matter-key-filter: guid
      file-glob-filter: "*.md"
    secrets: inherit
    
  tools:
    name: Tools
    needs: [pr-info, frontmatter, validate-toc]
    uses: OutSystems/tk-cicd/.github/workflows/documentation-build.yml@main
    secrets: inherit

  publish-dev:
    name: Publish Dev
    uses: OutSystems/tk-cicd/.github/workflows/auto-publish.yml@main
    needs: [pr-info, tools, validations]
    if: needs.pr-info.outputs.publish-dev == 'true'
    with:
      target-branch: ${{ vars.DEV_BRANCH }}
      pr-number: ${{ needs.pr-info.outputs.pull-request }}
      changed-files: ${{ needs.pr-info.outputs.changed-files }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  translations:
    name: Translations
    if: always() && needs.tools.result == 'success' && github.ref_name == github.event.repository.default_branch
    needs: [tools]
    uses: OutSystems/tk-cicd/.github/workflows/update-translations.yml@main
    with:
      event: docs-product
    secrets: inherit

  vector-db:
    name: VectorDB update
    if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
    uses: OutSystems/tk-cicd/.github/workflows/chroma-update.yml@main
    with:
      GITHUB_REPOSITORY: ${{ github.repository }}
      TK_CICD_BRANCH: 'main'
    secrets: inherit

  rdtkf-fix-pr-notify:
    name: Notify Slack
    if: github.event.action == 'labeled' && (github.event.label.name == 'ai-quick-fix' || github.event.label.name == 'ai-deep-fix')
    uses: OutSystems/tk-cicd/.github/workflows/quick-fix-pr-slack-notify.yml@main
    with:
      repository: ${{ github.repository }}
      pr_number: ${{ github.event.pull_request.number }}
      pr_url: ${{ github.event.pull_request.html_url }}
      pr_title: ${{ github.event.pull_request.title }}
      pr_description: ${{ github.event.pull_request.body || '' }}
      pr_label: ${{ github.event.label.name }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_TK_BOT_TOKEN }}

  qdrant-update:
    name: Qdrant update
    if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
    uses: OutSystems/tk-cicd/.github/workflows/qdrant-update.yml@main
    with:
      GITHUB_REPOSITORY: ${{ github.repository }}
    secrets: inherit
