name: Run

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - main
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled, ready_for_review, converted_to_draft]

concurrency:
  group: run-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Run
    uses: OutSystems/tk-cicd/.github/workflows/run.yml@main
    secrets: inherit
    with:
      translations-event: docs-product
      product-type: O11
