name: Validate Frontmatter

on:
  workflow_dispatch:
  workflow_call:

jobs:
  frontmatter-json-schema-validator:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Validate Frontmatter
        uses: mheap/frontmatter-json-schema-action@main
        with:
          paths: "src/**/*.md"
          schema_path: .github/workflows/frontmatter.json
