name: Validations

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY:
        required: true
        type: string
      PR_NUMBER:
        required: true
        type: string
      TK_CICD_BRANCH:
        required: true
        type: string

jobs:
  call_shared_workflow:
    name: Shared docs validations
    uses: OutSystems/tk-cicd/.github/workflows/validations.yml@main
    with:
      GITHUB_REPOSITORY: ${{ inputs.GITHUB_REPOSITORY }}
      PR_NUMBER: ${{ inputs.PR_NUMBER }}
      TK_CICD_BRANCH: ${{ inputs.TK_CICD_BRANCH }}
    secrets: inherit
