name: Update ALL Visual Assets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1-5"
  issue_comment:
    types: [created]

jobs:
  visual-assets-update-all:
    name: Update ALL Visual Assets
    uses: OutSystems/tk-cicd/.github/workflows/visual-assets-update-all.yml@main
    secrets: inherit
